'on':
  - push
  - pull_request
name: DynamoDB
jobs:
  Tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: 'amazon/dynamodb-local:latest'
        ports:
          - '8000:8000'
    strategy:
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
          - 1.16.x
          - 1.17.x
        platform:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run Test
        run: cd ./dynamodb && go test ./... -v -race
